#!/bin/sh

BASE=$(readlink -f $(dirname $0))
cd $BASE

for s in install.d/*; do
	. $s
	cd $BASE
done

# dotfiles
for i in $(ls dotfiles); do
	rm -rf ~/.$i
	cp -r dotfiles/$i ~/.$i
done

if [ -f private-vimrc ]; then
	# append private settings, place a private-vimrc in this directory
	cat private-vimrc >> ~/.vimrc
fi

if [ ! -d ~/bin ]; then
	mkdir ~/bin
fi

cp bin/* ~/bin

grep -q ".bash_custom" ~/.bashrc

if [ $? -ne 0 ]; then
	echo "adding bash_custom entry to your .bashrc"
	echo "if [ -f ~/.bash_custom ]; then . ~/.bash_custom; fi" >> ~/.bashrc
fi

