#!/bin/sh
info "composer..."

depends() {
	echo "php5-cli"
}

install() {
	if [ -x ~/bin/composer ]; then
		composer self-update;
	else 
		echo "installing composer..."
		curl -sS https://getcomposer.org/installer | php -- --install-dir=$HOME/bin > /dev/null
		mv $HOME/bin/composer.phar $HOME/bin/composer
	fi
}
