#!/bin/sh

depends() {
	echo "git vim"
}

install() {
	cd $BASE/git

	if [ ! -d vim-fugitive ]; then
		git clone https://github.com/tpope/vim-fugitive.git
		cd $BASE/dotfiles/vim/bundle
		ln -sf $BASE/git/vim-fugitive fugitive
	else
		cd vim-fugitive; 
		git pull origin master
	fi
}
