#!/bin/sh

[ ! -x /usr/bin/go ] && sudo apt-get install golang-go

[ ! -d ~/go ] && mkdir ~/go

if [ ! -d $BASE/git/vim-golang ]; then
	git clone https://github.com/jnwhiteh/vim-golang.git $BASE/git/vim-golang
fi

cd $BASE/git/vim-golang && git fetch && git reset --hard origin/master
[ ! -L $BASE/dotfiles/vim/bundle/vim-golang ] && \
	ln -s $BASE/git/vim-golang $BASE/dotfiles/vim/bundle/vim-golang

# install gocode
export GOTPATH=$HOME/go
go get -u github.com/nsf/gocode

mkdir -p "$BASE/dotfiles/vim/bundle/gocode/autoload"
mkdir -p "$BASE/dotfiles/vim/bundle/gocode/ftplugin/go"
cp "$GOPATH/src/github.com/nsf/gocode/vim/autoload/gocomplete.vim" "$BASE/dotfiles/vim/bundle/gocode/autoload"
cp "$GOPATH/src/github.com/nsf/gocode/vim/ftplugin/go/gocomplete.vim" "$BASE/dotfiles/vim/bundle/gocode/ftplugin/go"
