#!/bin/sh
info "phpcs..."

depends() {
	echo "php5-cli"
}

install() {
	if [ -x ~/bin/composer ]; then
		composer global require 'squizlabs/php_codesniffer=*'
	else 
		info "composer not installed, skipping..."
	fi
}
