#!/bin/sh
# based on https://powerline.readthedocs.org/en/latest/installation/linux.html#installation-linux

# compile libgit2 into relative dist path
# needs cmake
[ ! -x /usr/bin/cmake ] && sudo apt-get install cmake
if [ ! -d $BASE/git/libgit2 ]; then
	git clone https://github.com/libgit2/libgit2.git $BASE/git/libgit2 -b master
	# asssuming that cmake is installed
	cd $BASE/git/libgit2 &&	cmake -DCMAKE_INSTALL_PREFIX:PATH=$BASE/git/libgit2/dist . && make && make install	
fi

# bind pygit2 to the local libgit2 installation
# needs python-dev
if [ ! -d $BASE/git/pygit2 ]; then
	sudo apt-get install python-dev
	git clone git://github.com/libgit2/pygit2.git $BASE/git/pygit2
	cd $BASE/git/pygit2
	export LIBGIT2=$BASE/git/libgit2/dist 
	export LDFLAGS="-Wl,-rpath=$LIBGIT2/lib,--enable-new-dtags $LDFLAGS"
	python setup.py build
	python setup.py install --user
fi

pip install --user git+git://github.com/Lokaltog/powerline

[ ! -d ~/.fonts ] && mkdir ~/.fonts

if [ ! -f ~/.fonts/PowerlineSymbols.otf ]; then
	echo "installing powerline fonts..."

	wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf \
		-O ~/.fonts/PowerlineSymbols.otf

	fc-cache -vf ~/.fonts
	mkdir -p ~/.config/fontconfig/conf.d

	wget https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf \
		-O ~/.config/fontconfig/conf.d/10-powerline-symbols.conf 
fi
