#!/bin/sh
# from https://powerline.readthedocs.org/en/latest/installation/linux.html#installation-linux
[ ! -d ~/.fonts ] && mkdir ~/.fonts
if [ ! -f ~/.fonts/PowerlineSymbols.otf ]; then
	wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf \
		-O ~/.fonts/PowerlineSymbols.otf

	fc-cache -vf ~/.fonts
	mkdir -p ~/.config/fontconfig/conf.d

	wget https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf \
		-O ~/.config/fontconfig/conf.d/10-powerline-symbols.conf 
fi
