#!/bin/sh
info "spark..."

depends() {
	echo "git"
}

install() {
	if [ ! -x ~/bin/spark ]; then
		cd $BASE/git
		git clone https://github.com/holman/spark
	else
		cd $BASE/git/spark
		git pull
	fi

	cp $BASE/git/spark/spark ~/bin	
}
