#!/bin/sh
info "spark..."

depends() {
	echo "git"
}

install() {
	if [ ! -d $BASE/git/spark ]; then
		cd $BASE/git
		git clone https://github.com/holman/spark
	fi
	
	cd $BASE/git/spark
	git pull
	cp $BASE/git/spark/spark ~/bin
}
