#!/bin/sh
info "vim-rst-tables..."

if [ ! -x /usr/bin/pip ]; then
	warn "pip missing, skip installation"
	return
fi

pip install --user --upgrade vim_bridge
cd $BASE/git

if [ ! -d vim-rst-tables ]; then
	git clone git://github.com/nvie/vim-rst-tables.git
	cd $BASE/dotfiles/vim/bundle
	ln -sf $BASE/git/vim-rst-tables
else
	cd vim-rst-tables; 
	git pull origin master
fi
